jobs:
  - job: test
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - checkout: none
      - pwsh: |
          $token = '$(GitHub.Token)'
          $uri = '$(TIZEN_STUDIO_URL)'
          Invoke-WebRequest -Uri $uri -Headers @{"Authorization"="token $token"} -OutFile "tizen-studio.zip"
