jobs:
  - job: test
    pool:
      name: Hosted Windows 2019 with VS2019
    steps:
      - checkout: none
      - pwsh: |
          Invoke-WebRequest -Uri "$(TIZEN_STUDIO_URL)" -Headers @{"Authorization"="$(TIZEN_STUDIO_TOKEN)"} -OutFile "tizen-studio.zip"
